package provider.font;

import java.awt.*;
import java.util.Set;
import java.util.TreeSet;

public class FontProvider {

    public static Font getMono(){
        return getMonoLarge();
    }

    public static Font getMonoLarge(){
        return Fonts.LIBERATIONMONO_72;
    }

    public static Font getMonoSmall() { return Fonts.LIBERATIONMONO_9;}

    public static void printFonts(){
        String fonts[] = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();

        for ( int i = 0; i < fonts.length; i++ )
        {
            System.out.println(fonts[i]);
        }
    }

    public static void generateFontClass(){
        String fonts[] = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();

        Set<Integer> sizes = new TreeSet<>();
        sizes.add(9);
        sizes.add(18);
        sizes.add(36);
        sizes.add(72);
        for ( int i = 0; i < fonts.length; i++ )
        {
            for (int size : sizes){
                String varName = fonts[i].replaceAll(" ","").toUpperCase()+"_"+size;

                String code = "public static Font " + varName + " =  new Font(\""+fonts[i] + "\", Font.PLAIN, " +size+");";
                System.out.println(code);
            }

            //System.out.print(noSpaces + ", ");
        }
    }


    /*
    public enum Fonts{
        AAKAR, ABYSSINICASIL, ANI, ANJALIOLDLIPI, BITSTREAMCHARTER, CALADEA, CANTARELL, CARLITO, CENTURYSCHOOLBOOKL, CHANDAS, CHILANKA, COURIER, COURIER10PITCH, DEJAVUMATHTEXGYRE, DEJAVUSANS, DEJAVUSANSCONDENSED, DEJAVUSANSLIGHT, DEJAVUSANSMONO, DEJAVUSERIF, DEJAVUSERIFCONDENSED, DIALOG, DIALOGINPUT, DINGBATS, DROIDSANSFALLBACK, DYUTHI, FREEMONO, FREESANS, FREESERIF, GARGI, GARUDA, GENTIUM, GENTIUMBASIC, GENTIUMBOOKBASIC, GENTIUMALT, GUBBI, JAMRUL, KACSTART, KACSTBOOK, KACSTDECORATIVE, KACSTDIGITAL, KACSTFARSI, KACSTLETTER, KACSTNASKH, KACSTOFFICE, KACSTONE, KACSTPEN, KACSTPOSTER, KACSTQURN, KACSTSCREEN, KACSTTITLE, KACSTTITLEL, KALAPI, KALIMATI, KARUMBI, KERALEEYAM, KHMEROS, KHMEROSSYSTEM, KINNARI, LMMONOCAPS10, LMMONOLTCOND10, LMMONOLT10, LMMONOPROPLT10, LMMONOPROP10, LMMONOSLANT10, LMMONO10, LMROMANCAPS10, LMROMANDEMI10, LMROMANDUNH10, LMROMANSLANT10, LMROMANUNSL10, LMROMAN10, LMSANSDEMICOND10, LMSANSQUOT8, LMSANS10, LAKSAMAN, LATINMODERNMATH, LATO, LATOBLACK, LATOHAIRLINE, LATOHEAVY, LATOLIGHT, LATOMEDIUM, LATOSEMIBOLD, LATOTHIN, LIBERATIONMONO, LIBERATIONSANS, LIBERATIONSANSNARROW, LIBERATIONSERIF, LIKHAN, LINUXBIOLINUMKEYBOARDO, LINUXBIOLINUMO, LINUXLIBERTINEDISPLAYO, LINUXLIBERTINEINITIALSO, LINUXLIBERTINEMONOO, LINUXLIBERTINEO, LKLUG, LMMONO10, LMMONO12, LMMONO8, LMMONO9, LMMONOCAPS10, LMMONOLIGHT10, LMMONOLIGHTCOND10, LMMONOPROP10, LMMONOPROPLIGHT10, LMMONOSLANTED10, LMROMAN10, LMROMAN12, LMROMAN17, LMROMAN5, LMROMAN6, LMROMAN7, LMROMAN8, LMROMAN9, LMROMANCAPS10, LMROMANDEMI10, LMROMANDUNHILL10, LMROMANSLANTED10, LMROMANSLANTED12, LMROMANSLANTED17, LMROMANSLANTED8, LMROMANSLANTED9, LMROMANUNSLANTED10, LMSANS10, LMSANS12, LMSANS17, LMSANS8, LMSANS9, LMSANSDEMICOND10, LMSANSQUOT8, LOHITASSAMESE, LOHITBENGALI, LOHITDEVANAGARI, LOHITGUJARATI, LOHITGURMUKHI, LOHITKANNADA, LOHITMALAYALAM, LOHITODIA, LOHITTAMIL, LOHITTAMILCLASSICAL, LOHITTELUGU, LOMA, MANJARIBOLD, MANJARIREGULAR, MANJARITHIN, MATHJAX_AMS, MATHJAX_CALIGRAPHIC, MATHJAX_FRAKTUR, MATHJAX_MAIN, MATHJAX_MATH, MATHJAX_SANSSERIF, MATHJAX_SCRIPT, MATHJAX_SIZE1, MATHJAX_SIZE2, MATHJAX_SIZE3, MATHJAX_SIZE4, MATHJAX_TYPEWRITER, MATHJAX_VECTOR, MATHJAX_VECTOR-BOLD, MATHJAX_WINCHROME, MATHJAX_WINIE6, MEERA, MITRAMONO, MONOSPACED, MRY_KACSTQURN, MUKTINARROW, NAKULA, NAVILU, NIMBUSMONOL, NIMBUSROMANNO9L, NIMBUSSANSL, NORASI, NOTOCOLOREMOJI, NOTOKUFIARABIC, NOTOMONO, NOTONASKHARABIC, NOTONASKHARABICUI, NOTONASTALIQURDU, NOTOSANS, NOTOSANSADLAM, NOTOSANSADLAMUNJOINED, NOTOSANSANATOHIERO, NOTOSANSARABIC, NOTOSANSARABICUI, NOTOSANSARMENIAN, NOTOSANSAVESTAN, NOTOSANSBALINESE, NOTOSANSBAMUM, NOTOSANSBATAK, NOTOSANSBENGALI, NOTOSANSBENGALIUI, NOTOSANSBRAHMI, NOTOSANSBUGINESE, NOTOSANSBUHID, NOTOSANSCANADIANABORIGINAL, NOTOSANSCARIAN, NOTOSANSCHAKMA, NOTOSANSCHAM, NOTOSANSCHEROKEE, NOTOSANSCJKJPBOLD, NOTOSANSCJKJPREGULAR, NOTOSANSCJKKRBOLD, NOTOSANSCJKKRREGULAR, NOTOSANSCJKSCBOLD, NOTOSANSCJKSCREGULAR, NOTOSANSCJKTCBOLD, NOTOSANSCJKTCREGULAR, NOTOSANSCOPTIC, NOTOSANSCUNEIFORM, NOTOSANSCYPRIOT, NOTOSANSDESERET, NOTOSANSDEVANAGARI, NOTOSANSDEVANAGARIUI, NOTOSANSDISP, NOTOSANSEGYPTHIERO, NOTOSANSETHIOPIC, NOTOSANSGEORGIAN, NOTOSANSGLAGOLITIC, NOTOSANSGOTHIC, NOTOSANSGUJARATI, NOTOSANSGUJARATIUI, NOTOSANSGURMUKHI, NOTOSANSGURMUKHIUI, NOTOSANSHANUNOO, NOTOSANSHEBREW, NOTOSANSIMPARAMAIC, NOTOSANSINSPAHLAVI, NOTOSANSINSPARTHI, NOTOSANSJAVANESE, NOTOSANSKAITHI, NOTOSANSKANNADA, NOTOSANSKANNADAUI, NOTOSANSKAYAHLI, NOTOSANSKHAROSHTHI, NOTOSANSKHMER, NOTOSANSKHMERUI, NOTOSANSLAO, NOTOSANSLAOUI, NOTOSANSLEPCHA, NOTOSANSLIMBU, NOTOSANSLINEARB, NOTOSANSLISU, NOTOSANSLYCIAN, NOTOSANSLYDIAN, NOTOSANSMALAYALAM, NOTOSANSMALAYALAMUI, NOTOSANSMANDAIC, NOTOSANSMEETEIMAYEK, NOTOSANSMONGOLIAN, NOTOSANSMONO, NOTOSANSMONOCJKJPBOLD, NOTOSANSMONOCJKJPREGULAR, NOTOSANSMONOCJKKRBOLD, NOTOSANSMONOCJKKRREGULAR, NOTOSANSMONOCJKSCBOLD, NOTOSANSMONOCJKSCREGULAR, NOTOSANSMONOCJKTCBOLD, NOTOSANSMONOCJKTCREGULAR, NOTOSANSMYANMAR, NOTOSANSMYANMARUI, NOTOSANSN'KO, NOTOSANSNEWTAILUE, NOTOSANSOGHAM, NOTOSANSOLCHIKI, NOTOSANSOLDITALIC, NOTOSANSOLDTURKIC, NOTOSANSOLDPERSIAN, NOTOSANSOLDSOUARAB, NOTOSANSORIYA, NOTOSANSORIYAUI, NOTOSANSOSAGE, NOTOSANSOSMANYA, NOTOSANSPHAGSPA, NOTOSANSPHOENICIAN, NOTOSANSREJANG, NOTOSANSRUNIC, NOTOSANSSAMARITAN, NOTOSANSSAURASHTRA, NOTOSANSSHAVIAN, NOTOSANSSINHALA, NOTOSANSSINHALAUI, NOTOSANSSUNDANESE, NOTOSANSSYLOTINAGRI, NOTOSANSSYMBOLS, NOTOSANSSYMBOLS2, NOTOSANSSYRIACEASTERN, NOTOSANSSYRIACESTRANGELA, NOTOSANSSYRIACWESTERN, NOTOSANSTAGALOG, NOTOSANSTAGBANWA, NOTOSANSTAILE, NOTOSANSTAITHAM, NOTOSANSTAIVIET, NOTOSANSTAMIL, NOTOSANSTAMILUI, NOTOSANSTELUGU, NOTOSANSTELUGUUI, NOTOSANSTHAANA, NOTOSANSTHAI, NOTOSANSTHAIUI, NOTOSANSTIBETAN, NOTOSANSTIFINAGH, NOTOSANSUGARITIC, NOTOSANSVAI, NOTOSANSYI, NOTOSERIF, NOTOSERIFARMENIAN, NOTOSERIFBENGALI, NOTOSERIFCJKJP, NOTOSERIFCJKKR, NOTOSERIFCJKSC, NOTOSERIFCJKTC, NOTOSERIFDEVANAGARI, NOTOSERIFDISP, NOTOSERIFETHIOPIC, NOTOSERIFGEORGIAN, NOTOSERIFGUJARATI, NOTOSERIFHEBREW, NOTOSERIFKANNADA, NOTOSERIFKHMER, NOTOSERIFLAO, NOTOSERIFMALAYALAM, NOTOSERIFMYANMAR, NOTOSERIFSINHALA, NOTOSERIFTAMIL, NOTOSERIFTELUGU, NOTOSERIFTHAI, OPENDYSLEXIC, OPENDYSLEXICALTA, OPENDYSLEXICMONO, OPENSYMBOL, PADAUK, PADAUKBOOK, PADMAA, PADMAA-BOLD.1.1, PAGUL, PHETSARATHOT, POTHANA2000, PURISA, RACHANA, RAGHUMALAYALAM, REKHA, SAAB, SAHADEVA, SAMANATA, SAMYAKDEVANAGARI, SAMYAKGUJARATI, SAMYAKMALAYALAM, SAMYAKTAMIL, SANSSERIF, SARAI, SAWASDEE, SERIF, STANDARDSYMBOLSL, SURUMA, SYMBOLA, TEXGYREADVENTOR, TEXGYREBONUM, TEXGYRECHORUS, TEXGYRECURSOR, TEXGYREHEROS, TEXGYREHEROSCONDENSED, TEXGYREPAGELLA, TEXGYRESCHOLA, TEXGYRETERMES, TEXGYREBONUM, TEXGYREBONUMMATH, TEXGYREDEJAVUMATH, TEXGYREPAGELLAMATH, TEXGYRESCHOLAMATH, TEXGYRETERMESMATH, TEXGYREADVENTOR, TEXGYRECHORUS, TEXGYRECURSOR, TEXGYREHEROS, TEXGYREHEROSCN, TEXGYREPAGELLA, TEXGYRESCHOLA, TEXGYRETERMES, TIBETANMACHINEUNI, TIRESIASINFOFONT, TIRESIASINFOFONTZ, TIRESIASKEYFONTV2, TIRESIASLPFONT, TIRESIASPCFONT, TIRESIASPCFONTZ, TIRESIASSIGNFONT, TIRESIASSIGNFONTZ, TLWGTYPIST, TLWGTYPO, TLWGMONO, TLWGTYPEWRITER, UBUNTU, UBUNTUCONDENSED, UBUNTULIGHT, UBUNTUMONO, UMPUSH, UROOB, URWBOOKMANL, URWCHANCERYL, URWGOTHICL, URWPALLADIOL, UTKAL, UTOPIA, VEMANA2000, WAREE;
    }
    */


}
